baseURL = 'https://snigdha.dev/'
languageCode = 'en-us'
title = "Snigdha's space"
theme = "dream"

[params]
lightTheme = "caramellatte"
darkTheme = "forest"
avatar = "images/me.webp"
headerTitle = "Snigdha's space"
motto = "Dance along to the beat of your heart ❤︎"
footerBottomText = "❤︎"
reorderShares = []
showSummaryCoverInPost = true

favicon = "images/favicon.ico"

rss = true

[services]
[services.googleAnalytics]
ID = 'G-LG4JFS6MWF'

